name: Package Publish Download
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - run: echo '1.2.3' > version.txt
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: released-version
          path: version.txt

  Download:
    runs-on: ubuntu-latest

    needs:
      - Publish

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-version
          path: art
      - run: tree
      - run: cat art/version.txt
